name: List - Stage - All States
on:
  workflow_dispatch:
    inputs:
      ca:
        description: "CA"
        required: false
        default: true
        type: boolean
      mi:
        description: "MI"
        required: false
        default: true
        type: boolean
      co:
        description: "CO"
        required: false
        default: true
        type: boolean
      nj:
        description: "NJ"
        required: false
        default: true
        type: boolean
jobs:
  ca-tests-staging:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: staging-ca thelist-710labs.com
      ENV_ID: staging-ca
      EXECUTION_TYPE: ${{ github.event_name == 'workflow_dispatch' && 'Manual Run' || 'Scheduled Run' }}
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_STAGE }}
      RESULTS_URL: "https://710labs.github.io/seventen-functional-tests/"
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      NEXT_VERSION: true
      ADD_ADDRESS_BEFORE_CHECKOUT: true
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET}}
      DEFAULT_VIDEO_PREVIEW_URL: https://tymber-s3.imgix.net/herbnjoy-beverly-hills-350/product-brand-63616/d17157b5-8a90-48b1-aeb6-d0e092351548.png?s=480dd20057b2bd21b3b6d6200a3c0679
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "node"
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to CA
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_DEV }}${{ secrets.QA_ENDPOINT }}domains/update/?state=ca
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ci:test:staging:ca
  mi-tests-staging:
    timeout-minutes: 60
    needs: [ca-tests-staging]
    if: |
      always() &&
      (github.event_name == 'schedule' || github.event.inputs.mi == 'true')
    runs-on: ubuntu-latest
    env:
      ENV: staging-mi thelist-710labs.com
      ENV_ID: staging-mi
      EXECUTION_TYPE: Scheduled Run
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_STAGE }}
      RESULTS_URL: "https://710labs.github.io/seventen-functional-tests/"
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      NEXT_VERSION: true
      ADD_ADDRESS_BEFORE_CHECKOUT: true
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET}}
      DEFAULT_VIDEO_PREVIEW_URL: https://tymber-s3.imgix.net/herbnjoy-beverly-hills-350/product-brand-63616/d17157b5-8a90-48b1-aeb6-d0e092351548.png?s=480dd20057b2bd21b3b6d6200a3c0679
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to MI
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_DEV }}${{ secrets.QA_ENDPOINT }}domains/update/?state=mi
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ci:test:staging:mi
  co-tests-staging:
    timeout-minutes: 60
    needs: [mi-tests-staging]
    if: |
      always() &&
      (github.event_name == 'schedule' || github.event.inputs.co == 'true')
    runs-on: ubuntu-latest
    env:
      ENV: staging-co thelist-710labs.com
      ENV_ID: staging-co
      EXECUTION_TYPE: Scheduled Run
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_STAGE }}
      RESULTS_URL: "https://710labs.github.io/seventen-functional-tests/"
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      NEXT_VERSION: true
      ADD_ADDRESS_BEFORE_CHECKOUT: true
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to CO
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_DEV }}${{ secrets.QA_ENDPOINT }}domains/update/?state=co
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ci:test:staging:co
      - name: Set Domain to CA
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_DEV }}${{ secrets.QA_ENDPOINT }}domains/update/?state=ca
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
  nj-tests-staging:
    timeout-minutes: 60
    needs: [co-tests-staging]
    if: |
      always() &&
      (github.event_name == 'schedule' || github.event.inputs.nj == 'true')
    runs-on: ubuntu-latest
    env:
      ENV: staging-nj thelist-710labs.com
      ENV_ID: staging-ca
      EXECUTION_TYPE: Scheduled Run
      RUN_ID: ${{github.run_number}}
      UNIQUE_RUN_ID: ${{github.run_id}}
      ADMIN_USER: ${{ secrets.ADMIN_USER }}
      ADMIN_PW: ${{ secrets.ADMIN_PW }}
      API_KEY: ${{ secrets.API_KEY }}
      BASE_URL: ${{ secrets.BASE_URL_STAGE }}
      RESULTS_URL: "https://710labs.github.io/seventen-functional-tests/"
      QA_ENDPOINT: ${{ secrets.QA_ENDPOINT }}
      BYPASS_TAX_CALC: true
      NEXT_VERSION: true
      ADD_ADDRESS_BEFORE_CHECKOUT: true
      SLACK_BOT_USER_OAUTH_TOKEN: ${{ secrets.PW_TESTS_SLACKBOT_TOKEN}}
      S3_BUCKET: ${{ secrets.S3_BUCKET}}
      S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY}}
      S3_SECRET: ${{ secrets.S3_SECRET}}
      S3_REGION: ${{ secrets.S3_REGION}}
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET}}
      DEFAULT_VIDEO_PREVIEW_URL: https://tymber-s3.imgix.net/herbnjoy-beverly-hills-350/product-brand-63616/d17157b5-8a90-48b1-aeb6-d0e092351548.png?s=480dd20057b2bd21b3b6d6200a3c0679
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "node"
      - name: Install dependencies
        run: npm ci
      - name: Set Domain to NJ
        uses: JamesIves/fetch-api-data-action@v2.1.0
        with:
          endpoint: ${{ secrets.BASE_URL_DEV }}${{ secrets.QA_ENDPOINT }}domains/update/?state=nj
          configuration: '{ "method": "GET", "headers": {"x-api-key": "${{ secrets.API_KEY }}"} }'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run ci:test:staging:nj
